package:
  name: yb_sse_devices

workflows:
  - workflow_uuid: 3c8f1a62-9b74-4e2d-a5c1-7d0e8f4b2196
    source: yb_sse_devices/workflows/start_batch.py
  - workflow_uuid: 72cb4f07-9a92-46eb-ae2a-79d08e2c3b67
    source: yb_sse_devices/experiment_operations/synthesis_sampling.py
  - workflow_uuid: 871ecc8b-9e7c-4e09-8637-3c8c0df42927
    source: yb_sse_devices/experiment_operations/synthesis_load_tray.py
  - workflow_uuid: f7c79ca5-1ed4-4d2a-9571-a8bbf9786c44
    source: yb_sse_devices/workflows/synthesis_atomic_single.py
  - workflow_uuid: 7e5dabc1-8795-5009-85fe-c9a4c4f0c1e3
    source: yb_sse_devices/workflows/synthesis_batch.py
  - workflow_uuid: 00cdaee3-7c63-4c77-875d-3d7093d0e5e3
    source: yb_sse_devices/workflows/synthesis_powder_bead_cabin.py
  - workflow_uuid: 2b618ad2-cb04-4ce0-8f0f-4155497740b2
    source: yb_sse_devices/workflows/synthesis_powder_bead_rack2.py
  - workflow_uuid: bbf54bc0-4119-48be-a7b7-29d84a6a45a9
    source: yb_sse_devices/workflows/synthesis_mixing.py
