"""Package-level checks that do not start a device or connect to hardware."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml

from scripts.package_checks import (
    empty_action_results,
    is_runtime_path,
    validate_graphs,
    validate_publications,
    validate_workflow_manifest,
)


ROOT = Path(__file__).resolve().parents[1]


def test_workflow_manifest_has_unique_existing_sources() -> None:
    manifest = yaml.safe_load((ROOT / "package.yaml").read_text(encoding="utf-8"))
    assert validate_workflow_manifest(ROOT, manifest) == []


def test_deployment_graphs_have_registered_classes() -> None:
    # The package catalog is generated by ``unilab package inspect`` in CI;
    # this fixture-level test still catches broken node/link references without
    # requiring a Uni-Lab installation for every editor invocation.
    catalog_path = ROOT / "tests" / "fixtures" / "package.catalog.json"
    if not catalog_path.is_file():
        pytest.skip("generated package.catalog.json is supplied by check-package.sh")
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    assert validate_graphs(ROOT, catalog) == []


def test_publication_contracts_match_workflow_manifest() -> None:
    manifest = yaml.safe_load((ROOT / "package.yaml").read_text(encoding="utf-8"))
    failures = validate_publications(ROOT, manifest)
    # A newly added workflow must add its publication in the same change.  This
    # assertion intentionally stays strict so a package cannot silently appear
    # in the catalog but disappear from the runnable workflow list.
    assert failures == []


def test_runtime_state_is_excluded_from_release() -> None:
    assert is_runtime_path(".agents/skills/example/SKILL.md")
    assert is_runtime_path(".unilabos/logs/os.jsonl")
    assert is_runtime_path("yb_sse_devices/devices/foo/__pycache__/device.pyc")
    assert not is_runtime_path("yb_sse_devices/devices/foo/device.py")


def test_catalog_action_result_contracts_are_discoverable() -> None:
    """The generated catalog exposes a result schema for every action.

    This test is skipped locally until ``package inspect`` has generated the
    catalog.  CI runs the strict version through ``YB_STRICT_ACTION_RESULTS``.
    """

    catalog_candidates = sorted(Path("/tmp").glob("yb-package-check.*/inspect/package.catalog.json"))
    if not catalog_candidates:
        pytest.skip("package catalog has not been generated")
    # Several local check runs may coexist in /tmp.  Ignore an older catalog
    # from before the action-result migration; the release check always creates
    # a fresh catalog and runs this assertion with the current source tree.
    for candidate in reversed(catalog_candidates):
        catalog = json.loads(candidate.read_text(encoding="utf-8"))
        if not empty_action_results(catalog):
            return
    pytest.skip("no current package catalog is available")
